name: business_explorer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  http: ^1.2.0
  intl: ^0.19.0
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  mocktail: ^1.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: MontserratItalic
      fonts:
        - asset: assets/fonts/Montserrat-Italic.ttf

    - family: MontserratBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
